---
- name: Destroy Hypershift cluster in PowerVS
  shell: |
    set -o pipefail && \
    ./bin/hypershift destroy cluster powervs \
    --base-domain {{ base_domain }} \
    --resource-group {{ ibmcloud_resource_group }} \
    --infra-id {{ infra_id }} \
    --region {{ powervs_region }} \
    --zone {{ powervs_zone }} \
    --vpc-region {{ vpc_region }} \
    --name {{ hosted_cluster_name }}
  async: 1800
  poll: 10
  register: destroy
  ignore_errors: yes
  args:
    chdir: "{{ hypershift_dir }}"
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ mgmt_cluster_kubeconfig }}"


